name: Build and Test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: mxschmitt/action-tmate@v3
        with:
          detached: true

      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v3

      # Sparse checkout
      - name: Sparse checkout
        uses: ./
        with:
          sparse-checkout: |
            __test__
            .github
            dist
          path: sparse-checkout

      - name: Verify not disabled sparse checkout
        shell: bash
        run: set -x && ! ls -l sparse-checkout/src/git-command-manager.ts

      - name: Verify sparse checkout
        run: __test__/verify-sparse-checkout.sh

      # Sparse checkout (non-cone mode)
      # Disabled sparse checkout in existing checkout
      - name: Disabled sparse checkout
        uses: ./
        with:
          path: sparse-checkout

      - name: Verify disabled sparse checkout
        shell: bash
        run: set -x && ls -l sparse-checkout/src/git-command-manager.ts

      # Sparse checkout (non-cone mode)
      - name: Sparse checkout (non-cone mode)
        uses: ./
        with:
          sparse-checkout: |
            /__test__/
            /.github/
            /dist/
          sparse-checkout-cone-mode: false
          path: sparse-checkout-non-cone-mode

      - name: Verify sparse checkout (non-cone mode)
        run: __test__/verify-sparse-checkout-non-cone-mode.sh
